# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.12-slim

WORKDIR /app

# Install dependencies
COPY pyproject.toml .
COPY requirements.txt .
COPY main.py .
COPY uv.lock .

RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir .

# Default to local env
ENV ENVIRONMENT=remote

CMD ["python", "main.py"]
